### ISSUE TITLE
vsc 不能调试的问题

### ISSUE THREAD

**Issue by yuwancumian** [i5ting/wechat-dev-with-nodejs#20]
最近维护的一个express项目，用了大量的 let 来声明变量，开始用 node v.5.2.0 ，来跑的这个项目的时候，报错：SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
换成 node v6.2.0 ，项目就正常跑起了，
然而用vsc 调试的时候，环境选择Node.js 时候，也报以上的错误，
然后启动调试的时候，环境选择node 6.3 experiment ，结果报这个错误：
node --inspect=5728 --debug-brk --nolazy app.js 
node: bad option: --inspect=5728 ，
现在vsc 调试跑不起来，该如何设置呢，

**Comment by i5ting** [comment]
strict mode 增加'use strict'就可以了，估计是版本太高导致的

**Comment by yuwancumian** [comment]
解决了，，，二十几个文件每个头部加一个 'use strice'
谢啦桑大
